# Generated by Django 5.1.6 on 2025-02-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RegexPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100)),
                ('model_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.modelprovider')),
            ],
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
